const fs = require("fs");
const path = require("path");
require("dotenv").config();

// Detect environment flag (default: dev)
const envArgIndex = process.argv.findIndex((arg) => arg.startsWith("--env="));
const envFlag =
  envArgIndex >= 0 ? process.argv[envArgIndex].split("=")[1] : "dev";

const isProduction = envFlag === "prod";

// Resolve correct Angular env file path
const targetPath = isProduction
  ? path.join(__dirname, "src/environments/environment.prod.ts")
  : path.join(__dirname, "src/environments/environment.ts");

// Pull values from .env (fallbacks if missing)
const untappdUsername = process.env.UNTAPPD_USERNAME || "";
const useAWS = process.env.USE_AWS === "true";
const dataUrl = useAWS ? process.env.DATA_URL : "/assets/";
const ga4MeasurementId = process.env.GA4_MEASUREMENT_ID || "";

// Build full Angular environment file (always overwrite)
const envContent = `// Auto-generated by set-env.js
export const environment = {
  production: ${isProduction},
  useAWS: ${useAWS},
  dataUrl: '${dataUrl}',
  untappdUsername: '${untappdUsername}',
  ga4MeasurementId: '${ga4MeasurementId}'
};
`;

try {
  fs.writeFileSync(targetPath, envContent, { flag: "w" });
  console.log(`✅ Successfully wrote environment config to ${targetPath}`);
} catch (err) {
  console.error(`❌ Error writing to ${targetPath}:`, err);
  process.exit(1);
}
